# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('Project_ID', models.IntegerField(null=True)),
                ('Project_Title', models.CharField(max_length=120, null=True)),
                ('Project_Type', models.CharField(max_length=120, null=True)),
                ('Project_Post', models.CharField(max_length=120, null=True)),
                ('Project_Suburb', models.CharField(max_length=120, null=True)),
                ('Project_State', models.CharField(max_length=120, null=True)),
                ('Project_Stage', models.CharField(max_length=120, null=True)),
                ('Project_Category', models.CharField(max_length=120, null=True)),
                ('PROJ_STATUST_DESC', models.CharField(max_length=120, null=True)),
                ('PROJ_START_DATE_DETAIL', models.CharField(max_length=120, null=True)),
                ('PROJ_END_DATE_DETAIL', models.CharField(max_length=120, null=True)),
                ('PROJ_VALUE', models.IntegerField(null=True)),
                ('PROJ_VALUE_DESC', models.CharField(max_length=120, null=True)),
                ('PROJ_DETAIL_TEXT', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
