# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='address',
            new_name='city',
        ),
    ]
